name: SkyWars
version: 1.0
main: com.sky.SkyPlugin
description: Un emocionante plugin de SkyWars con recompensas, tienda y kits mejorables.
commands:
  join:
    description: Unirse a un equipo.
  createarena:
    description: Crear una nueva arena.
  startgame:
    description: Iniciar un juego manualmente.
  endgame:
    description: Finalizar el juego actual.
  selectkit:
    description: Seleccionar un kit.
  stats:
    description: Ver estadísticas del jugador.
  leaderboard:
    description: Ver la tabla de clasificación.
  claimdailyreward:
    description: Reclamar la recompensa diaria.
  buy:
    description: Comprar un objeto en la tienda.
